# Продакшен переопределения
services:
  frontend:
    environment:
      - REACT_APP_API_URL=http://antisingle.fvds.ru:8001/api
    volumes: []  # Убрать все volumes для продакшена

  backend:
    volumes:
      - ./data:/app/data  # Только данные, не код
