services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
      - backend_db:/app
    environment:
      - DATABASE_URL=sqlite:///./socfinder.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  backend_db:
