services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=socfinder
      - POSTGRES_USER=socfinder_user
      - POSTGRES_PASSWORD=Ant1$1ngleoe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U socfinder_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    environment:
    - DATABASE_URL=postgresql://socfinder_user:Ant1$1ngleoe@postgres:5432/socfinder
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://antisingle.fvds.ru:8001/api
    depends_on:
      - backend
    volumes: []
#      - ./frontend/src:/app/src
#      - ./frontend/public:/app/public

volumes:
  postgres_data:
